site_name: SPARQLess
site_url: https://mff-uk.github.io/sparqless/
repo_url: https://github.com/mff-uk/sparqless

nav:
  - Home: 'index.md'
  - 'User Guide':
    - Usage: 'usage.md'
    - Configuration: 'configuration.md'
  - 'How it works':
    - Overview: 'overview.md'
    - Observation: 'observation.md'
    - Parsing: 'model_parsing.md'
    - Postprocessing: 'postprocessing.md'
    - 'Schema Creation': 'schema.md'
    - Querying: 'querying.md'
    - 'Model Checkpointing': 'model_checkpointing.md'
    - 'Hot Reloading': 'hot_reloading.md'
  - 'Developer Guide':
    - Development: 'development.md'
    - 'Editing documentation': 'editing_documentation.md'

theme:
  name: readthedocs
  locale: en
  titles_only: True

plugins:
  - with-pdf:
      author: Daniel Crha
      copyright: Charles University
      cover_subtitle: Bringing RDF datasets to all developers
      output_path: pdf/documentation.pdf
