@startuml
actor User
collections Config as config.ts
participant Observation
participant "Model Parsing"
participant Postprocessing
participant "Schema Creation"
database "GraphQL Server"

User --> config.ts: Configure application

config.ts -> Observation: Configuration

rnote over Observation
  Collect observations
  about SPARQL endpoint
endrnote

Observation -> "Model Parsing": RDF Observations

rnote over "Model Parsing"
  Build model
  from observations
endrnote

"Model Parsing" -> Postprocessing: Data Model

rnote over Postprocessing
  Run postprocessing hooks
  on model descriptors
endrnote

Postprocessing -> "Schema Creation": Data Model

rnote over "Schema Creation"
  Generate GraphQL schema
endrnote

"Schema Creation" -> "GraphQL Server": GraphQL Schema

rnote over "GraphQL Server"
  Run GraphQL server
endrnote

User --> "GraphQL Server": Browse schema and build queries

@enduml
