name: ci
on:
  push:
    branches:
      - "master"
      - "feature/add-docker-image-to-ci"  # TODO: remove the test branch
  pull_request:

jobs:
  check-and-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.13.0"
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - run: npm run lint
      - run: npm test
